### ISSUE TITLE
Не уходят запросы в API

### ISSUE THREAD

**Issue by deviatovae** [hel-sidoruk/rs-clone#58]
Приоритет: **BLOCKER**

Шаги:
1. Зайти на задеплоенную версию сайта - https://rs-codewars-clone.netlify.app/
1. Открыть dev-tools на вкладке Network
1. Нажать signup

Текущий результат:
- Запрос не отправляется, ошибка `ERR_SSL_PROTOCOL_ERROR`

Ожидаемый результат:
- Запрос отправляется без ошибок

Варианты решения:
1. Поменять протокол в ссылке к апи на http, что не очень безопасно
1. Использовать бесплатный сертификат через cloudflare, но возможно там потребуется свой домен

**Comment by hel-sidoruk** [comment]
Спасибо за комментарий) Мы в курсе, сейчас эта проблема решается. Пока она решается, поменяла ссылку для запросов на деплой сервера на render.com, но там иногда очень долго обрабатываются запросы
